title: The Energy Museum
author:
  name: Energy Museum Team
  email: 'info@energymuseum.org'
metadata:
    description: 'Explore the fascinating world of energy through immersive digital exhibitions, interactive experiences, and visual storytelling.'
    keywords: 'energy, museum, digital exhibitions, renewable energy, science, education, sustainability'
blog:
  route: '/exhibitions'

